version: '3'
services:
  agent1:
    image: jetbrains/teamcity-agent
    container_name: agent1
    environment:
      - AGENT_NAME=agent1
      - SERVER_URL="CUSTOM URL WHERE THE TEAMCITY SERVER HAS BEEN HOSTED"
    volumes:
      - /etc/volumes/teamcity/agents:/data/teamcity_agent/conf
      - /etc/volumes/.teamcitydata/:/root/
    network_mode: host
    privileged: true
